
export const shortname = {
  //'MUFC': 'http://icons.iconarchive.com/icons/giannis-zographos/english-football-club/256/Manchester-United-icon.png',
  'Manchester City FC': 'Man City',
  'Liverpool FC':  'Liverpool',
  'Tottenham Hotspur FC': 'Tottenham',
  'Everton FC':  'Everton',
  'Chelsea FC':  'Chelsea',
  'Leicester City FC': 'Leicester',
  'Watford FC':  'Watford',
  'Southampton FC':  'Southampton',
  'AFC Bournemouth': 'Bournemouth',
  'Arsenal FC': 'Arsenal',
  'West Bromwich Albion FC':  'West Brom',
  'Brighton & Hove Albion':  'Brighton',
  'Manchester United FC':  'Man United',
  'Stoke City FC':  'Stoke',
  'Crystal Palace FC':  'Crystal Palace',
  'Burnley FC': 'Burnley',
  'Newcastle United FC': 'Newcastle',
  'Swansea City FC':  'Swansea',
  'Huddersfield Town':  'Huddersfield',
  'West Ham United FC':  'West Ham'
};

export const teamlogo = {
  'Manchester United FC': 'Manchester-United-icon.png',
  'Swansea City FC':  'Swansea-City-icon.png',
  'Leicester City FC': 'Leicester-City-icon.png',
  'Everton FC':  'Everton-FC-icon.png',
  'West Ham United FC':  'West-Ham-United-icon.png',
  'Tottenham Hotspur FC': 'Tottenham-Hotspur-icon.png',
  'West Bromwich Albion FC':  'West-Bromwich-Albion-icon.png',
  'Watford FC':  'watford-icon.png',
  'Huddersfield Town':  'Huddersfield-icon.png',
  'Brighton & Hove Albion':  'Brighton-icon.png',
  'Stoke City FC': 'Stoke-City-icon.png',
  'Arsenal FC':  'Arsenal-FC-icon.png',
  'Crystal Palace FC':  'Crystal-Palace-icon.png',
  'Liverpool FC':  'Liverpool-FC-icon.png',
  'Southampton FC':  'Southampton-FC-icon.png',
  'Newcastle United FC': 'Newcastle-United-icon.png',
  'Manchester City FC': 'Manchester-City-icon.png',
  'Burnley FC':  'Burnley-FC-icon.png',
  'Chelsea FC':  'Chelsea-FC-icon.png',
  'AFC Bournemouth': 'Bournemouth-icon.png',
};
